#!/bin/bash

# Homebrew
set -e
brew update -v
brew outdated

set +e
brew upgrade
brew cleanup

# Python
set -e
pip install --upgrade pip setuptools
pip list | cut -d ' ' -f 1 | xargs pip3 install --upgrade

pip3 install --upgrade pip setuptools wheel
pip3 list | cut -d ' ' -f 1 | xargs pip3 install --upgrade

# Ruby
rvm version | grep latest && echo "rvm seems to be up to date" || rvm get stable
ruby -e ' \
  known=`rvm list known_strings | grep ^ruby-[[:digit:]]`.split;
  inst=`rvm list | grep ruby- | cut -d " " -f 2`.split;
  newer=[]
  known.each do |v|
    if inst.none? { |i| i >= v }
      newer << v
    end
  end
  if newer.any?
    puts "New rubies available:"
    puts newer
  end
'
